Add Home and About responsive pages
dennis-every/arubyconf pull request #1
Opened 2023-01-03 11:59 UTC by dennis-every

- Add index.html, index.css, and app.js files

2023-01-04 16:56 UTC, Qoosim requested changes
#  *Status: Required Changes* :recycle:

Hi @dennis-every, 

Good job so far!
There are some issues that you still need to work on to prepare your project for the final evaluation but you are almost there!

#  Top Highlights
-  No linter errors. :heavy_check_mark: 
-  Good README file. :heavy_check_mark: 
-  Correct GitHub Flow. :heavy_check_mark: 
-  Awesome UI. :heavy_check_mark: 

![](https://user-images.githubusercontent.com/80612925/157397398-00904e26-60ec-46cd-9510-240661c250ef.gif)


## Suggested changes
_Check the comments under the review._

You can use as many of my suggestions as you want. If there is anything you would like to skip - feel free to do that. However, I strongly recommend you to take them into account as they can make your code better._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

- [ ] You've done great job in your video presentation, but one thing  is missing in that presentation. You're required to highlight a piece of the code that you find interesting or  proud of making. Kindly include this in your presentation. Great job man.

2023-01-04 16:56 UTC, Qoosim commented on assets/stylesheets/index.css
> +}
- [ ] It is required to produce a close replica of the guiding template. Your project looks awesome, but you need to look into the margin left  and right of the speaker section compare to what we have on the guiding design. You should also try to look into the space between each speaker picture and the text next it. At the moment, the space on your design is too wide compare to what we have on the guiding template. Kindly compare and adjust your design.

#### Your Design
![your-design-speaker-desktop](https://user-images.githubusercontent.com/26597432/210599599-632db714-cfbd-4135-86f6-ed5c48be7162.png)

### Guiding Template
![temp-speaker-section-desktop](https://user-images.githubusercontent.com/26597432/210599640-b9f711cc-bf24-4d93-8392-4b3dbd5e49eb.png)

2023-01-04 16:56 UTC, Qoosim commented on assets/stylesheets/index.css
> +}
- [ ] For the mobile version of the same speaker section, there is margin-bottom for each of the speaker for the readability purpose. But there is no such a margin on your design for that particular section which makes defeat the readability feature for that section. Kindly compare your design with the guiding template and work your project along side the guiding template.

### Your Design
![your-speaker-mobile](https://user-images.githubusercontent.com/26597432/210602030-b33610e8-ddfd-497d-80f3-27b939538891.png)

### Guiding template
![temp-speaker-mobile](https://user-images.githubusercontent.com/26597432/210602097-eefab8b7-90f0-4e4e-944f-c05b64806fd3.png)

- [ ] I would also recommend you to add margin left and right for it to look like the original design

2023-01-04 16:56 UTC, Qoosim commented on about.html
> +        <h1>Global summit 2023</h1>
- [ ] To follow html best practice, there should be only one `h1` tag in each page of any website. You can use `<br />` to divide your main title or another approach. Kindly remove one `h1` tag and find a way to make it look the same without repeating the same `h1` tag twice.

2023-01-04 16:56 UTC, Qoosim commented on index.html
> +        <h1>Main Program</h1>
- [ ] It is html best practice to have only one main title in a webpage which you already have one up. Kindly use any of the remaining heading `hx (2, 3, 4, 5, 6).`

2023-01-04 16:56 UTC, Qoosim commented on index.html
> +        <h1>Featured Speakers</h1>
- [ ] It is html best practice to have only one main title in a webpage which you already have one up. Kindly use any of the remaining heading `hx (2, 3, 4, 5, 6).`

2023-01-05 11:36 UTC, ichala approved these changes
Hi @dennis-every   ,
# Status: Approved :heavy_check_mark: :heavy_check_mark: :heavy_check_mark:  
 
![68747470733a2f2f6d65646961322e67697068792e636f6d2f6d656469612f6c3366516333614356304871707a5763552f67697068792e676966](https://user-images.githubusercontent.com/85113567/184604589-430cf4bc-1d2e-4603-976a-7a48a899ea35.gif)

# To Highlight 💪🏻

- Changes Implemented ✔️ 


 Good job implementing the requirements  :+1: Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

# Optional Suggestions  :

- N/A


**********
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._
Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag  ichala in your question so I can receive the notification.


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-01-05 11:41 UTC, merged